FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY package.json .
COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./


CMD ["npm", "run", "start"]



# docker run -it -p 3000:3000 -v  /home/node/app/node_modules -v $(pwd):/home/node/app  IMAGE_ID
#  volumes:
#       - /home/node/app/node_modules
#       - .:/home/node/app
#   web:
#     stdin_open: true
# Bobby the saviour
# docker run -it -p 3000:3000 -v /home/node/app/node_modules -v ~/my-project-directory:/home/node/app IMAGE_ID